# TCL File Generated by Component Editor 16.0
# Tue Mar 07 13:50:02 BRT 2017
# DO NOT MODIFY


# 
# autocorrelation "autocorrelation" v1.0
#  2017.03.07.13:50:02
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module autocorrelation
# 
set_module_property DESCRIPTION ""
set_module_property NAME autocorrelation
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME autocorrelation
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL autocorrelation
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file autocorrelation.vhd VHDL PATH AutoCorrelacao/src/autocorrelation.vhd TOP_LEVEL_FILE
add_fileset_file FifoDualClk4x16.vhd VHDL PATH AutoCorrelacao/src/FifoDualClk4x16.vhd
add_fileset_file Ram4x16.vhd VHDL PATH AutoCorrelacao/src/Ram4x16.vhd
add_fileset_file acAccumulator.vhd VHDL PATH AutoCorrelacao/src/acAccumulator.vhd
add_fileset_file acControlUnit.vhd VHDL PATH AutoCorrelacao/src/acControlUnit.vhd
add_fileset_file acDataMultiplexer.vhd VHDL PATH AutoCorrelacao/src/acDataMultiplexer.vhd
add_fileset_file acMultipleAdder.vhd VHDL PATH AutoCorrelacao/src/acMultipleAdder.vhd
add_fileset_file ac_correlation_result_buffer.vhd VHDL PATH AutoCorrelacao/src/ac_correlation_result_buffer.vhd
add_fileset_file ac_frame_buffer.vhd VHDL PATH AutoCorrelacao/src/ac_frame_buffer.vhd
add_fileset_file ac_media_temporal_calc.vhd VHDL PATH AutoCorrelacao/src/ac_media_temporal_calc.vhd
add_fileset_file ac_multiplier_acc_unit.vhd VHDL PATH AutoCorrelacao/src/ac_multiplier_acc_unit.vhd
add_fileset_file avalonSlaveDecoder.vhd VHDL PATH AutoCorrelacao/src/avalonSlaveDecoder.vhd
add_fileset_file dataInterface.vhd VHDL PATH AutoCorrelacao/src/dataInterface.vhd
add_fileset_file lupa_library.vhd VHDL PATH AutoCorrelacao/src/lupa_library.vhd


# 
# parameters
# 
add_parameter mode NATURAL 1
set_parameter_property mode DEFAULT_VALUE 1
set_parameter_property mode DISPLAY_NAME mode
set_parameter_property mode TYPE NATURAL
set_parameter_property mode UNITS None
set_parameter_property mode ALLOWED_RANGES 0:2147483647
set_parameter_property mode HDL_PARAMETER true
add_parameter PARALLELISM_DEPTH NATURAL 1
set_parameter_property PARALLELISM_DEPTH DEFAULT_VALUE 1
set_parameter_property PARALLELISM_DEPTH DISPLAY_NAME PARALLELISM_DEPTH
set_parameter_property PARALLELISM_DEPTH TYPE NATURAL
set_parameter_property PARALLELISM_DEPTH UNITS None
set_parameter_property PARALLELISM_DEPTH ALLOWED_RANGES 0:2147483647
set_parameter_property PARALLELISM_DEPTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 8192
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 acSlaveRead read Input 1
add_interface_port avalon_slave_0 acSlaveWrite write Input 1
add_interface_port avalon_slave_0 acSlaveAddress address Input 13
add_interface_port avalon_slave_0 acSlaveByteEnable byteenable Input 4
add_interface_port avalon_slave_0 acSlaveWriteData writedata Input 32
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 acSlaveWaitRequest waitrequest Output 1
add_interface_port avalon_slave_0 acSlaveReadDataValid readdatavalid Output 1
add_interface_port avalon_slave_0 acSlaveReadData readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset nrst reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master acMasterAddress address Output 32
add_interface_port avalon_master acMasterBurstCount burstcount Output 4
add_interface_port avalon_master acMasterByteEnable byteenable Output 1
add_interface_port avalon_master acMasterRead read Output 1
add_interface_port avalon_master acMasterReadData readdata Input 8
add_interface_port avalon_master acMasterReadDataValid readdatavalid Input 1
add_interface_port avalon_master acMasterWaitRequest waitrequest Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end dataBeingWrittenToExternalMemory databeingwrittentoexternalmemory Input 1
add_interface_port conduit_end enableSensorDataToExternalMemory enablesensordatatoexternalmemory Output 1
add_interface_port conduit_end memoryControllerBusy memorycontrollerbusy Input 1

