# TCL File Generated by Component Editor 16.1
# Fri Mar 31 21:49:49 BRT 2017
# DO NOT MODIFY


# 
# bridge_stSrcMmMaster "bridge_stSrcMmMaster" v1.0
#  2017.03.31.21:49:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bridge_stSrcMmMaster
# 
set_module_property DESCRIPTION ""
set_module_property NAME bridge_stSrcMmMaster
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bridge_stSrcMmMaster
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bridge_stSrc_mmMaster
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bridge_stSrc_mmMaster.vhd VHDL PATH src/bridge_stSrc_mmMaster.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter COLS INTEGER 640 ""
set_parameter_property COLS DEFAULT_VALUE 640
set_parameter_property COLS DISPLAY_NAME COLS
set_parameter_property COLS WIDTH ""
set_parameter_property COLS TYPE INTEGER
set_parameter_property COLS UNITS None
set_parameter_property COLS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COLS DESCRIPTION ""
set_parameter_property COLS HDL_PARAMETER true
add_parameter LINES INTEGER 480
set_parameter_property LINES DEFAULT_VALUE 480
set_parameter_property LINES DISPLAY_NAME LINES
set_parameter_property LINES TYPE INTEGER
set_parameter_property LINES UNITS None
set_parameter_property LINES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LINES HDL_PARAMETER true
add_parameter NBITS_ADDR INTEGER 32 ""
set_parameter_property NBITS_ADDR DEFAULT_VALUE 32
set_parameter_property NBITS_ADDR DISPLAY_NAME NBITS_ADDR
set_parameter_property NBITS_ADDR WIDTH ""
set_parameter_property NBITS_ADDR TYPE INTEGER
set_parameter_property NBITS_ADDR UNITS None
set_parameter_property NBITS_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_ADDR DESCRIPTION ""
set_parameter_property NBITS_ADDR HDL_PARAMETER true
add_parameter NBITS_DATA INTEGER 8 ""
set_parameter_property NBITS_DATA DEFAULT_VALUE 8
set_parameter_property NBITS_DATA DISPLAY_NAME NBITS_DATA
set_parameter_property NBITS_DATA WIDTH ""
set_parameter_property NBITS_DATA TYPE INTEGER
set_parameter_property NBITS_DATA UNITS None
set_parameter_property NBITS_DATA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_DATA DESCRIPTION ""
set_parameter_property NBITS_DATA HDL_PARAMETER true
add_parameter NBITS_BURST INTEGER 4 ""
set_parameter_property NBITS_BURST DEFAULT_VALUE 4
set_parameter_property NBITS_BURST DISPLAY_NAME NBITS_BURST
set_parameter_property NBITS_BURST WIDTH ""
set_parameter_property NBITS_BURST TYPE INTEGER
set_parameter_property NBITS_BURST UNITS None
set_parameter_property NBITS_BURST ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_BURST DESCRIPTION ""
set_parameter_property NBITS_BURST HDL_PARAMETER true
add_parameter NBITS_BYTEEN INTEGER 4
set_parameter_property NBITS_BYTEEN DEFAULT_VALUE 4
set_parameter_property NBITS_BYTEEN DISPLAY_NAME NBITS_BYTEEN
set_parameter_property NBITS_BYTEEN TYPE INTEGER
set_parameter_property NBITS_BYTEEN UNITS None
set_parameter_property NBITS_BYTEEN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_BYTEEN HDL_PARAMETER true
add_parameter BURST INTEGER 1 ""
set_parameter_property BURST DEFAULT_VALUE 1
set_parameter_property BURST DISPLAY_NAME BURST
set_parameter_property BURST TYPE INTEGER
set_parameter_property BURST UNITS None
set_parameter_property BURST ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST DESCRIPTION ""
set_parameter_property BURST HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_mem
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_waitrequest waitrequest Input 1
add_interface_port avalon_master master_address address Output nbits_addr
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_writedata writedata Output nbits_data


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink st_datain data Input nbits_data
add_interface_port avalon_streaming_sink st_datavalid valid Input 1
add_interface_port avalon_streaming_sink st_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink st_ready ready Output 1
add_interface_port avalon_streaming_sink st_startofpacket startofpacket Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point clock_mem
# 
add_interface clock_mem clock end
set_interface_property clock_mem clockRate 0
set_interface_property clock_mem ENABLED true
set_interface_property clock_mem EXPORT_OF ""
set_interface_property clock_mem PORT_NAME_MAP ""
set_interface_property clock_mem CMSIS_SVD_VARIABLES ""
set_interface_property clock_mem SVD_ADDRESS_GROUP ""

add_interface_port clock_mem clk_mem clk Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 8
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 1
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_chipselect chipselect Input 1
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_address address Input 1
add_interface_port slave slave_writedata writedata Input 32
add_interface_port slave slave_waitrequest waitrequest Output 1
add_interface_port slave slave_readdatavalid readdatavalid Output 1
add_interface_port slave slave_readdata readdata Output 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0

