# TCL File Generated by Component Editor 16.1
# Thu Feb 21 16:45:49 BRT 2019
# DO NOT MODIFY


# 
# lwir_ul0304 "lwir_ul0304" v1.0
#  2019.02.21.16:45:49
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module lwir_ul0304
# 
set_module_property DESCRIPTION ""
set_module_property NAME lwir_ul0304
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lwir_ul0304
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lwir_ul0304_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lwir_ul0304_avalon.vhd VHDL PATH src/lwir_ul0304/lwir_ul0304_avalon.vhd TOP_LEVEL_FILE
add_fileset_file lwir_ul0304_core.vhd VHDL PATH src/lwir_ul0304/lwir_ul0304_core.vhd


# 
# parameters
# 
add_parameter NUM_COLS INTEGER 320
set_parameter_property NUM_COLS DEFAULT_VALUE 320
set_parameter_property NUM_COLS DISPLAY_NAME NUM_COLS
set_parameter_property NUM_COLS TYPE INTEGER
set_parameter_property NUM_COLS UNITS None
set_parameter_property NUM_COLS HDL_PARAMETER true
add_parameter NUM_ROWS INTEGER 256
set_parameter_property NUM_ROWS DEFAULT_VALUE 256
set_parameter_property NUM_ROWS DISPLAY_NAME NUM_ROWS
set_parameter_property NUM_ROWS TYPE INTEGER
set_parameter_property NUM_ROWS UNITS None
set_parameter_property NUM_ROWS HDL_PARAMETER true
add_parameter NBITS_PXL INTEGER 8
set_parameter_property NBITS_PXL DEFAULT_VALUE 8
set_parameter_property NBITS_PXL DISPLAY_NAME NBITS_PXL
set_parameter_property NBITS_PXL TYPE INTEGER
set_parameter_property NBITS_PXL UNITS None
set_parameter_property NBITS_PXL HDL_PARAMETER true


# 
# display items
# 


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock_sink
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 1
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_chipselect chipselect Input 1
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_address address Input 1
add_interface_port slave slave_byteenable byteenable Input 4
add_interface_port slave slave_writedata writedata Input 32
add_interface_port slave slave_waitrequest waitrequest Output 1
add_interface_port slave slave_readdatavalid readdatavalid Output 1
add_interface_port slave slave_readdata readdata Output 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point st
# 
add_interface st avalon_streaming start
set_interface_property st associatedClock clock_sink
set_interface_property st associatedReset reset_sink
set_interface_property st dataBitsPerSymbol 8
set_interface_property st errorDescriptor ""
set_interface_property st firstSymbolInHighOrderBits true
set_interface_property st maxChannel 0
set_interface_property st readyLatency 0
set_interface_property st ENABLED true
set_interface_property st EXPORT_OF ""
set_interface_property st PORT_NAME_MAP ""
set_interface_property st CMSIS_SVD_VARIABLES ""
set_interface_property st SVD_ADDRESS_GROUP ""

add_interface_port st st_endofpacket endofpacket Output 1
add_interface_port st st_data_out data Output 8
add_interface_port st st_data_valid valid Output 1
add_interface_port st st_startofpacket startofpacket Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink sensor_clk_in clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end lwir_dataIn datain Input nbits_pxl
add_interface_port conduit_end lwir_syt syt Output 1
add_interface_port conduit_end lwir_syl syl Output 1
add_interface_port conduit_end lwir_syp syp Output 1

