# TCL File Generated by Component Editor 16.1
# Tue Mar 26 19:35:56 BRT 2019
# DO NOT MODIFY


# 
# nuc_one_point "nuc_one_point" v1.0
#  2019.03.26.19:35:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module nuc_one_point
# 
set_module_property DESCRIPTION ""
set_module_property NAME nuc_one_point
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME nuc_one_point
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nuc_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file nuc_avalon.vhd VHDL PATH src/nuc/nuc_avalon.vhd TOP_LEVEL_FILE
add_fileset_file nuc_core.vhd VHDL PATH src/nuc/nuc_core.vhd
add_fileset_file readPacketsAvalon.vhd VHDL PATH src/nuc/readPacketsAvalon.vhd
add_fileset_file delay_regs.vhd VHDL PATH src/utils/delay_regs.vhd
add_fileset_file reg.vhd VHDL PATH src/utils/reg.vhd
add_fileset_file mean_frame.vhd VHDL PATH src/nuc/mean_frame.vhd


# 
# parameters
# 
add_parameter NBITS_ADDR INTEGER 32
set_parameter_property NBITS_ADDR DEFAULT_VALUE 32
set_parameter_property NBITS_ADDR DISPLAY_NAME NBITS_ADDR
set_parameter_property NBITS_ADDR TYPE INTEGER
set_parameter_property NBITS_ADDR UNITS None
set_parameter_property NBITS_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_ADDR HDL_PARAMETER true
add_parameter NBITS_PACKETS INTEGER 32
set_parameter_property NBITS_PACKETS DEFAULT_VALUE 32
set_parameter_property NBITS_PACKETS DISPLAY_NAME NBITS_PACKETS
set_parameter_property NBITS_PACKETS TYPE INTEGER
set_parameter_property NBITS_PACKETS UNITS None
set_parameter_property NBITS_PACKETS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_PACKETS HDL_PARAMETER true
add_parameter FIFO_SIZE INTEGER 1024
set_parameter_property FIFO_SIZE DEFAULT_VALUE 1024
set_parameter_property FIFO_SIZE DISPLAY_NAME FIFO_SIZE
set_parameter_property FIFO_SIZE TYPE INTEGER
set_parameter_property FIFO_SIZE UNITS None
set_parameter_property FIFO_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_SIZE HDL_PARAMETER true
add_parameter FIFO_SIZE_BITS INTEGER 10
set_parameter_property FIFO_SIZE_BITS DEFAULT_VALUE 10
set_parameter_property FIFO_SIZE_BITS DISPLAY_NAME FIFO_SIZE_BITS
set_parameter_property FIFO_SIZE_BITS TYPE INTEGER
set_parameter_property FIFO_SIZE_BITS UNITS None
set_parameter_property FIFO_SIZE_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_SIZE_BITS HDL_PARAMETER true
add_parameter NBITS_DATA INTEGER 8
set_parameter_property NBITS_DATA DEFAULT_VALUE 8
set_parameter_property NBITS_DATA DISPLAY_NAME NBITS_DATA
set_parameter_property NBITS_DATA TYPE INTEGER
set_parameter_property NBITS_DATA UNITS None
set_parameter_property NBITS_DATA ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_DATA HDL_PARAMETER true
add_parameter NBITS_BURST INTEGER 4
set_parameter_property NBITS_BURST DEFAULT_VALUE 4
set_parameter_property NBITS_BURST DISPLAY_NAME NBITS_BURST
set_parameter_property NBITS_BURST TYPE INTEGER
set_parameter_property NBITS_BURST UNITS None
set_parameter_property NBITS_BURST ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_BURST HDL_PARAMETER true
add_parameter NBITS_BYTEEN INTEGER 4
set_parameter_property NBITS_BYTEEN DEFAULT_VALUE 4
set_parameter_property NBITS_BYTEEN DISPLAY_NAME NBITS_BYTEEN
set_parameter_property NBITS_BYTEEN TYPE INTEGER
set_parameter_property NBITS_BYTEEN UNITS None
set_parameter_property NBITS_BYTEEN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_BYTEEN HDL_PARAMETER true
add_parameter BURST INTEGER 8
set_parameter_property BURST DEFAULT_VALUE 8
set_parameter_property BURST DISPLAY_NAME BURST
set_parameter_property BURST TYPE INTEGER
set_parameter_property BURST UNITS None
set_parameter_property BURST ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST HDL_PARAMETER true
add_parameter ADDR_BASE_READ STD_LOGIC_VECTOR 940572672
set_parameter_property ADDR_BASE_READ DEFAULT_VALUE 940572672
set_parameter_property ADDR_BASE_READ DISPLAY_NAME ADDR_BASE_READ
set_parameter_property ADDR_BASE_READ WIDTH 32
set_parameter_property ADDR_BASE_READ TYPE STD_LOGIC_VECTOR
set_parameter_property ADDR_BASE_READ UNITS None
set_parameter_property ADDR_BASE_READ ALLOWED_RANGES 0:4294967295
set_parameter_property ADDR_BASE_READ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point st_src
# 
add_interface st_src avalon_streaming start
set_interface_property st_src associatedClock clock_mem
set_interface_property st_src associatedReset reset_sink
set_interface_property st_src dataBitsPerSymbol 8
set_interface_property st_src errorDescriptor ""
set_interface_property st_src firstSymbolInHighOrderBits true
set_interface_property st_src maxChannel 0
set_interface_property st_src readyLatency 0
set_interface_property st_src ENABLED true
set_interface_property st_src EXPORT_OF ""
set_interface_property st_src PORT_NAME_MAP ""
set_interface_property st_src CMSIS_SVD_VARIABLES ""
set_interface_property st_src SVD_ADDRESS_GROUP ""

add_interface_port st_src st_src_endofpacket endofpacket Output 1
add_interface_port st_src st_src_data data Output nbits_data
add_interface_port st_src st_src_datavalid valid Output 1
add_interface_port st_src st_src_ready ready Input 1
add_interface_port st_src st_src_startofpacket startofpacket Output 1


# 
# connection point slave_1
# 
add_interface slave_1 avalon end
set_interface_property slave_1 addressUnits WORDS
set_interface_property slave_1 associatedClock clock_mem
set_interface_property slave_1 associatedReset reset_sink
set_interface_property slave_1 bitsPerSymbol 8
set_interface_property slave_1 burstOnBurstBoundariesOnly false
set_interface_property slave_1 burstcountUnits WORDS
set_interface_property slave_1 explicitAddressSpan 0
set_interface_property slave_1 holdTime 0
set_interface_property slave_1 linewrapBursts false
set_interface_property slave_1 maximumPendingReadTransactions 1
set_interface_property slave_1 maximumPendingWriteTransactions 0
set_interface_property slave_1 readLatency 0
set_interface_property slave_1 readWaitTime 1
set_interface_property slave_1 setupTime 0
set_interface_property slave_1 timingUnits Cycles
set_interface_property slave_1 writeWaitTime 0
set_interface_property slave_1 ENABLED true
set_interface_property slave_1 EXPORT_OF ""
set_interface_property slave_1 PORT_NAME_MAP ""
set_interface_property slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property slave_1 SVD_ADDRESS_GROUP ""

add_interface_port slave_1 slave_chipselect chipselect Input 1
add_interface_port slave_1 slave_read read Input 1
add_interface_port slave_1 slave_write write Input 1
add_interface_port slave_1 slave_address address Input 3
add_interface_port slave_1 slave_byteenable byteenable Input nbits_byteen
add_interface_port slave_1 slave_writedata writedata Input 32
add_interface_port slave_1 slave_waitrequest waitrequest Output 1
add_interface_port slave_1 slave_readdatavalid readdatavalid Output 1
add_interface_port slave_1 slave_readdata readdata Output 32
set_interface_assignment slave_1 embeddedsw.configuration.isFlash 0
set_interface_assignment slave_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink st_sink_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink st_sink_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink st_sink_datain data Input nbits_data
add_interface_port avalon_streaming_sink st_sink_datavalid valid Input 1
add_interface_port avalon_streaming_sink st_sink_ready ready Output 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_mem
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master masterrd_address address Output nbits_addr
add_interface_port avalon_master masterrd_burstcount burstcount Output 4
add_interface_port avalon_master masterrd_read read Output 1
add_interface_port avalon_master masterrd_readdata readdata Input nbits_data
add_interface_port avalon_master masterrd_readdatavalid readdatavalid Input 1
add_interface_port avalon_master masterrd_waitrequest waitrequest Input 1


# 
# connection point clock_mem
# 
add_interface clock_mem clock end
set_interface_property clock_mem clockRate 0
set_interface_property clock_mem ENABLED true
set_interface_property clock_mem EXPORT_OF ""
set_interface_property clock_mem PORT_NAME_MAP ""
set_interface_property clock_mem CMSIS_SVD_VARIABLES ""
set_interface_property clock_mem SVD_ADDRESS_GROUP ""

add_interface_port clock_mem clk_mem clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1

