# TCL File Generated by Component Editor 16.1
# Fri Feb 22 16:38:55 BRT 2019
# DO NOT MODIFY


# 
# swir_v400 "swir_v400" v1.0
#  2019.02.22.16:38:55
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module swir_v400
# 
set_module_property DESCRIPTION ""
set_module_property NAME swir_v400
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME swir_v400
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL swir_controller_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file swir_controller_avalon.vhd VHDL PATH src/swir/swir_controller_avalon.vhd TOP_LEVEL_FILE
add_fileset_file swir_controller_core.vhd VHDL PATH src/swir/swir_controller_core.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock pxl_clk
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 1
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_chipselect chipselect Input 1
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_address address Input 1
add_interface_port slave slave_byteenable byteenable Input 4
add_interface_port slave slave_writedata writedata Input 32
add_interface_port slave slave_waitrequest waitrequest Output 1
add_interface_port slave slave_readdatavalid readdatavalid Output 1
add_interface_port slave slave_readdata readdata Output 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point st
# 
add_interface st avalon_streaming start
set_interface_property st associatedClock pxl_clk
set_interface_property st associatedReset reset_sink
set_interface_property st dataBitsPerSymbol 8
set_interface_property st errorDescriptor ""
set_interface_property st firstSymbolInHighOrderBits true
set_interface_property st maxChannel 0
set_interface_property st readyLatency 0
set_interface_property st ENABLED true
set_interface_property st EXPORT_OF ""
set_interface_property st PORT_NAME_MAP ""
set_interface_property st CMSIS_SVD_VARIABLES ""
set_interface_property st SVD_ADDRESS_GROUP ""

add_interface_port st st_endofpacket endofpacket Output 1
add_interface_port st st_data_out data Output 8
add_interface_port st st_data_valid valid Output 1
add_interface_port st st_startofpacket startofpacket Output 1


# 
# connection point pxl_clk
# 
add_interface pxl_clk clock end
set_interface_property pxl_clk clockRate 0
set_interface_property pxl_clk ENABLED true
set_interface_property pxl_clk EXPORT_OF ""
set_interface_property pxl_clk PORT_NAME_MAP ""
set_interface_property pxl_clk CMSIS_SVD_VARIABLES ""
set_interface_property pxl_clk SVD_ADDRESS_GROUP ""

add_interface_port pxl_clk pxl_clk_in clk Input 1


# 
# connection point sensor_clk
# 
add_interface sensor_clk clock end
set_interface_property sensor_clk clockRate 0
set_interface_property sensor_clk ENABLED true
set_interface_property sensor_clk EXPORT_OF ""
set_interface_property sensor_clk PORT_NAME_MAP ""
set_interface_property sensor_clk CMSIS_SVD_VARIABLES ""
set_interface_property sensor_clk SVD_ADDRESS_GROUP ""

add_interface_port sensor_clk sensor_clk_in clk Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock pxl_clk
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end swir_clk_out sensor_clk Output 1
add_interface_port conduit_end swir_dataIn datain Input 8
add_interface_port conduit_end swir_fsync fsync Output 1
add_interface_port conduit_end swir_lsync lsync Output 1
add_interface_port conduit_end swir_pclk_out swir_pxl_clk_out Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock pxl_clk
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1

