ALL:
	vcom conv_package.vhd | grep Err 
	vcom conv_core.vhd | grep Err	
	vcom conv_core_tb.vhd | grep Err
	vcom window_gen.vhd | grep Err
	vcom window_gen_tb.vhd | grep Err
	vcom conv_avalon.vhd | grep Err
	vcom conv_avalon_tb.vhd | grep Err
